project:
  type: book

book:
  title: "Practical Computing"
  author: "Srikar CV"
  date: "1/3/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - GitHub.ipynb
    - Lassajous_curves.ipynb
    - How_to_create_a_quarto_book.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



